services:
  nut-dashboard:
    image: ghcr.io/bermanbt/nut-dashboard:latest
    container_name: nut-dashboard
    restart: unless-stopped
    network_mode: host
#    ports: 8080:8080
    environment:
      - UPS1_HOST=localhost
      - UPS1_PORT=3493
      - UPS1_NAME=your-ups-name-1
      - UPS1_LABEL=Rack UPS
      - UPS1_USER=monuser
      - UPS1_PASSWORD=changeme
      - UPS2_HOST=192.168.1.20
      - UPS2_PORT=3493
      - UPS2_NAME=your-ups-name-2
      - UPS2_LABEL=NAS UPS
      - UPS2_USER=monuser
      - UPS2_PASSWORD=changeme
