services:
  nut-dashboard:
    image: ghcr.io/bermanbt/nut-dashboard:latest
    container_name: nut-dashboard
    restart: unless-stopped
    network_mode: host
#    ports: 8080:8080
    environment:
      - UPS1_HOST=localhost
      - UPS1_PORT=3493
      - UPS1_NAME=Racked-UPS
      - UPS1_LABEL=Rack UPS
      - UPS1_USER=local_mon
      - UPS1_PASSWORD=[removed]
      - UPS2_HOST=10.0.1.3
      - UPS2_PORT=3493
      - UPS2_NAME=ups
      - UPS2_LABEL=NAS/Lab UPS
      - UPS2_USER=monuser
      - UPS2_PASSWORD=[removed]
